name: GitHub workflow

# Controls when the workflow will run
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            -   name: GitHub workflow
                uses: appleboy/ssh-action@master
                with:
                    #ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                    host: ${{ vars.HOST }}
                    username: ${{ vars.SSHUSER }}
                    password: ${{ secrets.PASSWORD }}
                    port: 22
                    script: |
                        cd ${{ vars.PATH }}
                        git status
                        git diff
                        git checkout -- composer.lock
                        git checkout -- package-lock.json
                        git pull
                        chown -R ${{ vars.USER }}:www-data ./*
                        chown -R ${{ vars.USER }}:www-data ./.[^.]*
                        composer update
                        npm update
                        composer dump-autoload -o
                        php bin/console cache:pool:clear --all
                        php bin/console cache:clear
                        chown -R ${{ vars.USER }}:www-data ./*
                        chown -R ${{ vars.USER }}:www-data ./.[^.]*
                        php bin/console doctrine:migrations:migrate --no-interaction --verbose
                        php bin/console doctrine:migrations:diff --no-interaction
                        git status
